version: "3.3"
services:
  nuxt:
    container_name: nuxt
    build: './nuxt'
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - server
    volumes:
      - "/opt/volumes/uploads:/opt/builder/static/static"
  manage-ui:
    container_name: manage-ui
    build: './manage-ui'
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - server
    volumes:
      - "/opt/volumes/uploads:/opt/default/dist/static"
  server:
    container_name: server
    build: './server'
    restart: always
    ports:
      - 3000:3000
      - 3002:3002
    depends_on:
      - mysql
      - redis
    volumes:
      - "/opt/volumes/uploads:/opt/server/uploads"
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/opt/volumes/mysql:/var/lib/mysql"
