version: "3.3"
services:
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    user: root
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - "/etc/localtime:/etc/localtime"
  node_exporter:
    image: prom/node-exporter:v1.1.2
    container_name: node_exporter
    restart: always
    network_mode: host
    pid: host
    user: root
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
      - "/etc/localtime:/etc/localtime"
  grafana:
    image: grafana/grafana:7.5.5
    container_name: grafana
    restart: always
    ports:
      - 3001:3001
    user: root
    volumes:
      - '/opt/grafana-storage:/var/lib/grafana'
      - './grafana.ini:/etc/grafana/grafana.ini'
